#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.18
#  in conjunction with Tcl version 8.6
#    Nov 06, 2018 11:09:19 AM -03  platform: Darwin

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

ZEBRA_TEST_ZPL = '^XA\
^FO20,10^GB700,1,3^FS\
^CFA,30\
^AV,30,30^FO20,30^FD***Mercury Team***^FS\
^AV,30,30^FO20,130^FD***Zebra Printer***^FS\
^AV,30,30^FO20,230^FD***Connection Test***^FS\
^FO20,330^GB700,1,3^FS\
^XZ'

if __name__ == '__main__':
    import badgesapp.py
    badgesapp.py.vp_start_gui()
